language: generic

sudo: required
services:
  - docker

before_install:
  - docker build  .

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "dockerapi"
  env: "Dockerapi-env"
  bucket_name: "resources"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
